# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{data_table}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Aufreiter"]
  s.date = %q{2010-04-12}
  s.description = %q{Smart export of arbitrary ruby object collections}
  s.email = %q{ma@zive.at}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "data_table.gemspec",
     "lib/data_table.rb",
     "test/helper.rb",
     "test/test_data_table.rb"
  ]
  s.homepage = %q{http://github.com/michael/data_table}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Smart export of arbitrary ruby object collections}
  s.test_files = [
    "test/helper.rb",
     "test/test_data_table.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, ["~> 1.5.3"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.10.3"])
    else
      s.add_dependency(%q<fastercsv>, ["~> 1.5.3"])
      s.add_dependency(%q<shoulda>, ["~> 2.10.3"])
    end
  else
    s.add_dependency(%q<fastercsv>, ["~> 1.5.3"])
    s.add_dependency(%q<shoulda>, ["~> 2.10.3"])
  end
end

